<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <a href="/users/<?= $user->getId() ?>"><?= htmlspecialchars($user->getName()) ?></a>
            </td>
            <td>
                <?= htmlspecialchars($user->getEmail()) ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<?php if($page > 1): ?>
    <a href="/users?page=<?= $page - 1?>">назад</a>
<?php endif; ?>
<?php if($page < $pages): ?>
    <a href="/users?page=<?= $page + 1?>">вперед</a>
<?php endif; ?>
